"""Тексты SEO-страниц Жолдас на трех языках (ru, kk, en): шапка, подписи, FAQ, описания групп знаков.
Числа и данные (вопросы, знаки, категории) подставляет tools/build_seo.py. Длинное тире запрещено: только дефис.
Форматирование: {n_q}, {n_signs}, {n_topics}, {n_cat}, {date} подставляются через str.format."""

LANGS = ('ru', 'kk', 'en')
PREFIX = {'ru': '', 'kk': '/kk', 'en': '/en'}
HTML_LANG = {'ru': 'ru', 'kk': 'kk', 'en': 'en'}
OG_LOCALE = {'ru': 'ru_KZ', 'kk': 'kk_KZ', 'en': 'en_US'}
LANG_LABEL = {'kk': 'Қаз', 'ru': 'Рус', 'en': 'Eng'}
LANG_NAME = {'kk': 'Қазақша', 'ru': 'Русский', 'en': 'English'}

# slug тем: одинаковые во всех языках
TOPIC_SLUG = {
    'm01': 'general-provisions', 'm02': 'driver-duties', 'm03': 'pedestrians-passengers', 'm04': 'traffic-lights',
    'm05': 'special-signals', 'm06': 'maneuvering', 'm07': 'speed', 'm08': 'overtaking', 'm09': 'stopping-parking',
    'm10': 'level-crossings-motorways', 'm11': 'intersections', 'm12': 'route-vehicles-lights', 'm13': 'towing-learner-driving',
    'm14': 'passengers-cargo', 'm15': 'bicycles-scooters-columns', 'm16': 'first-aid', 'm17': 'liability-fines',
    'm18': 'road-signs', 'm19': 'road-markings', 'm20': 'safe-driving', 'm21': 'motorcycles', 'm22': 'trucks',
    'm23': 'buses', 'm24': 'trailers', 'm25': 'tram-trolleybus',
}

TXT = {
    'ru': {
        'name': 'Жолдас', 'name_full': 'Жолдас ПДД', 'crumb_home': 'Главная', 'updated': 'Обновлено',
        'nav': {'exam': 'Экзамен', 'categories': 'Категории', 'signs': 'Знаки', 'topics': 'Темы', 'faq': 'Вопросы', 'about': 'О проекте'},
        'nav_label': 'Разделы сайта', 'lang_label': 'Язык', 'cta': 'Начать подготовку', 'cta_login': 'Войти',
        'cta_note': 'Регистрация по номеру телефона. Учебные материалы без оплаты.',
        'foot': 'Жолдас - индивидуальная подготовка к экзамену ПДД РК по всем категориям. Учебный материал по ПДД РК (Приказ МВД РК № 534, ред. 2026), не официальное издание. Официальный текст Правил - на',
        'foot_check': 'Перед экзаменом сверяйтесь с eGov и вашим спецЦОН.',
        'privacy': 'Конфиденциальность',
        'home_title': 'Жолдас ПДД: подготовка к экзамену на права в Казахстане 2026',
        'home_desc': '{n_topics} {w_topics}, {n_q} {w_q} с разбором и схемами, {n_signs} {w_signs}, пробный экзамен как в спецЦОН. Личный план подготовки по всем {n_cat} категориям ПДД РК 2026. Бесплатно.',
        'home_h1': 'Подготовка к экзамену на права в Казахстане',
        'home_lead': 'Жолдас - индивидуальная подготовка к теории ПДД РК 2026 по всем {n_cat} категориям, от A1 до Tm. Личный план по дате экзамена, учебник, {n_q} {w_q} с разбором и схемами ситуаций, работа над ошибками и пробный экзамен в формате спецЦОН: 40 вопросов, 40 минут, минимум 32 верных ответа.',
        'home_points': [
            'Личный план на каждый день по дате экзамена и категории',
            'Учебник: {n_topics} {w_topics} по ПДД РК простым языком',
            '{n_q} {w_q} с разбором, ссылкой на пункт Правил и схемами',
            '{n_signs} {w_signs} с названиями и значениями',
            'Работа над ошибками: трудные вопросы возвращаются, пока не закрепятся',
            'Три языка: казахский, русский, английский',
        ],
        'home_explore': 'Что можно узнать без регистрации',
        'home_explore_links': [('exam', 'Как проходит экзамен на права в Казахстане: теория, практика, пересдачи'),
                               ('categories', 'Все категории прав от A1 до Tm: возраст, стаж, требования'),
                               ('signs', 'Дорожные знаки Казахстана с названиями и значениями'),
                               ('topics', 'Темы ПДД РК: главное и типичные ошибки'),
                               ('faq', 'Ответы на частые вопросы об экзамене')],
        'exam_title': 'Экзамен на права в Казахстане 2026: теория, практика, пересдачи',
        'exam_desc': 'Как сдать экзамен на права в Казахстане в 2026: теория (40 вопросов, 40 минут, 32 верных), практика на автодроме спецЦОН, пошаговый путь к правам, сроки пересдач и изменения 2026 года.',
        'exam_h1': 'Экзамен на права в Казахстане в 2026 году',
        'exam_lead': 'Кратко: теория - 40 вопросов за 40 минут, для сдачи нужно минимум 32 верных ответа; практика проходит на автоматизированном автодроме спецЦОН. Ниже - как устроен путь к правам, какие правила действуют при пересдаче и что изменилось в 2026 году.',
        'exam_facts': ['Вопросов в тесте', 'Минут на тест', 'Минимум верных ответов', 'Язык теории', 'Срок действия результата'],
        'exam_theory': 'Теоретический экзамен', 'exam_practical': 'Практический экзамен', 'exam_steps': 'Путь к правам по шагам',
        'exam_retakes': 'Пересдачи', 'exam_changes': 'Что изменилось в 2026 году', 'exam_sources': 'Источники', 'exam_status': 'Статус',
        'exam_where': 'Где проходит', 'exam_scoring': 'Как оценивается',
        'cats_title': 'Категории водительских прав в Казахстане: A1, A, B1, B, BE, C1, C, D1, D, Tb, Tm',
        'cats_desc': 'Все {n_cat} категорий и подкатегорий прав в Казахстане: какие транспортные средства, с какого возраста, нужен ли стаж, как сдаются теория и практика. Справочник по ПДД РК 2026.',
        'cats_h1': 'Категории водительских прав в Казахстане',
        'cats_lead': 'В Казахстане {n_cat} категорий и подкатегорий прав: от мотоциклов (A1, A, B1) до легковых автомобилей (B, BE), грузовых (C1, C, C1E, CE), автобусов (D1, D, D1E, DE), троллейбусов и трамваев (Tb, Tm). Выберите категорию, чтобы увидеть возраст, стаж и порядок экзаменов.',
        'cats_col': ['Категория', 'Транспортные средства', 'Возраст', 'Стаж'],
        'cat_sections': {'vehicles': 'Какие транспортные средства', 'age': 'Минимальный возраст', 'experience': 'Стаж вождения',
                         'theory': 'Теоретический экзамен', 'practical': 'Практический экзамен', 'where': 'Где проходит',
                         'car': 'Экзаменационное транспортное средство', 'exercises': 'Упражнения', 'sources': 'Официальные источники'},
        'cat_title': '{name}: возраст, стаж, экзамен | Жолдас ПДД',
        'cat_other': 'Другие категории',
        'signs_title': 'Дорожные знаки Казахстана с названиями и значениями 2026',
        'signs_desc': 'Каталог дорожных знаков Казахстана: {n_signs} {w_signs} в семи группах, от предупреждающих до табличек. Название, значение и пояснение к каждому знаку.',
        'signs_h1': 'Дорожные знаки Казахстана',
        'signs_lead': 'Каталог дорожных знаков по Приложению 1 к ПДД РК: {n_signs} {w_signs} в семи группах. Откройте знак, чтобы увидеть точное название, значение, пояснение и вопросы экзамена, где он встречается.',
        'sign_title': 'Знак {code} «{name}» - значение | Жолдас ПДД',
        'sign_h1': 'Дорожный знак {code} «{name}»',
        'sign_intro': 'Знак {code} «{name}» относится к группе «{group}».',
        'sign_labels': {'code': 'Номер', 'name': 'Название', 'group': 'Группа', 'meaning': 'Значение', 'note': 'Пояснение', 'related': 'Похожие знаки из этой группы',
                        'questions': 'Вопросы экзамена по этому знаку', 'answer': 'Правильный ответ', 'explain': 'Разбор', 'all': 'Все дорожные знаки', 'img': 'Дорожный знак'},
        'group_blurb': {
            'Предупреждающие знаки': 'Предупреждают о приближении к опасному участку дороги. Водитель должен принять меры, соответствующие обстановке.',
            'Знаки приоритета': 'Устанавливают очередность проезда перекрестков, пересечений проезжих частей и узких участков дороги.',
            'Запрещающие знаки': 'Вводят или отменяют ограничения движения: запрет въезда, обгона, остановки, ограничение скорости, массы, габаритов.',
            'Предписывающие знаки': 'Указывают обязательные направления движения или разрешают движение только определенным транспортным средствам.',
            'Информационно-указательные знаки': 'Вводят или отменяют режим движения и сообщают о расположении населенных пунктов и объектов.',
            'Знаки сервиса': 'Сообщают о расположении объектов обслуживания: медпункта, заправки, места отдыха.',
            'Знаки дополнительной информации (таблички)': 'Уточняют или ограничивают действие знаков, с которыми применяются: расстояние, зона и время действия, вид транспортного средства.',
        },
        'topics_title': 'Темы ПДД РК: краткий разбор каждого раздела Правил',
        'topics_desc': '{n_topics} {w_topics} по ПДД РК 2026: общие положения, скорость, обгон, перекрестки, знаки, разметка, первая помощь, штрафы. По каждой теме - главное и типичные ошибки.',
        'topics_h1': 'Темы ПДД РК',
        'topics_lead': 'Учебник Жолдас разбит на {n_topics} {w_topics}. Здесь - краткое содержание каждой: главные правила со ссылками на пункты и типичные ошибки водителей.',
        'topic_title': '{title} - ПДД РК: главное и типичные ошибки | Жолдас',
        'topic_sections': {'facts': 'Главное', 'mistakes': 'Типичные ошибки', 'minutes': 'Время на изучение: {n} мин.', 'rules': 'Разделы Правил', 'more': 'Другие темы',
                           'full': 'Полный урок, вопросы с разбором и схемами доступны после регистрации.', 'all': 'Все темы'},
        'topic_cats': 'Для категорий',
        'faq_title': 'Вопросы и ответы об экзамене на права в Казахстане | Жолдас ПДД',
        'faq_desc': 'Сколько вопросов на теории, сколько минут, сколько нужно верных ответов, как пересдать, с какого возраста права, нужна ли регистрация. Ответы по ПДД РК 2026.',
        'faq_h1': 'Частые вопросы об экзамене на права',
        'faq_lead': 'Ответы основаны на Правилах приема экзаменов и выдачи водительских удостоверений (редакция июля 2026) и на Законе «О дорожном движении». Информация справочная: перед экзаменом проверьте условия на eGov и в вашем спецЦОН.',
        'faq': [
            ('Сколько вопросов и времени на теоретическом экзамене в Казахстане?',
             'В тесте 40 вопросов, на все дается 40 минут. Чтобы сдать, нужно ответить правильно минимум на 32 вопроса, то есть можно ошибиться не больше 8 раз (п. 16, 17, 23 Правил приема экзаменов).'),
            ('На каком языке можно сдавать теорию?',
             'Язык теста выбираете вы: казахский, русский или английский (п. 16). Иностранцы, не владеющие казахским или русским, могут сдавать теорию с квалифицированным переводчиком (п. 6).'),
            ('Сколько действует результат теоретического экзамена?',
             'Положительный результат теории действует 2 года с момента получения (п. 23 Правил в редакции 2026 года).'),
            ('Как проходит практический экзамен?',
             'Практика проходит на автоматизированном автодроме спецЦОН на экзаменационной машине с датчиками и видеокамерами. Результат выставляет автоматическая система: за ошибки начисляются штрафные баллы, при 100 баллах экзамен прекращается и ставится «не сдал» (методика автодрома).'),
            ('С какого возраста можно получить права категории B?',
             'С 18 лет (ст. 74 Закона «О дорожном движении»). Прошедших подготовку по направлению местных органов военного управления допускают к экзамену с 17 лет, удостоверение выдают с 18 лет.'),
            ('Через сколько можно пересдать экзамен на права?',
             'Первую пересдачу назначают на следующий рабочий день. После двух неудачных попыток следующая возможна не раньше чем через месяц (п. 11-2). Если на теории нарушили правила (подсказки, телефон, выход из зала), пересдача не раньше чем через 3 месяца (п. 24).'),
            ('Что нужно для записи на экзамен?',
             'Медицинская справка формы № 073/у, свидетельство об окончании курса в организации обучения вождению и запись через портал eGov, приложение eGov Mobile или ЦОН. При записи проходит биометрическая идентификация (п. 6, 11-1, 11-2).'),
            ('Нужна ли регистрация в Жолдас и сколько это стоит?',
             'Один пробный тест из 40 вопросов можно пройти без регистрации. Чтобы учиться по личному плану, с учебником и вопросами с разбором, нужна регистрация по номеру телефона. Обучение в Жолдас бесплатное.'),
            ('Это официальные вопросы спецЦОН?',
             'Нет. Официальная база вопросов не публикуется. Жолдас - учебный материал по действующим ПДД РК: вопросы составлены по тексту Правил, у каждого указан пункт. Пробный экзамен повторяет формат настоящего: 40 вопросов, 40 минут, минимум 32 верных ответа.'),
            ('Сколько вопросов в Жолдас и для каких категорий?',
             'В банке {n_q} {w_q} с разбором и схемами, {n_signs} {w_signs} и {n_topics} {w_topics}. Охвачены все {n_cat} категорий: A1, A, B1, B, BE, C1, C, C1E, CE, D1, D, D1E, DE, Tb, Tm. Вопросы по особенностям категории показываются только тем, кому они нужны.'),
        ],
        'about_title': 'О проекте Жолдас: бесплатная подготовка к экзамену ПДД РК',
        'about_desc': 'Что такое Жолдас: индивидуальная подготовка к теории ПДД Казахстана на казахском, русском и английском. Как устроен курс, откуда материалы и как проверяется точность.',
        'about_h1': 'О проекте Жолдас',
        'about_sections': [
            ('Что это', 'Жолдас (по-казахски «попутчик») - сайт для подготовки к экзамену на водительские права в Казахстане. Он помогает выучить ПДД РК 2026 по личному плану: с учебником, вопросами с разбором и схемами ситуаций, работой над ошибками и пробным экзаменом в формате спецЦОН.'),
            ('Для кого', 'Для тех, кто готовится к теории на любую из {n_cat} категорий, от A1 до Tm, и хочет заниматься на казахском, русском или английском языке. Обучение бесплатное, нужна только регистрация по номеру телефона.'),
            ('Откуда материалы', 'Материалы составлены по Правилам дорожного движения РК (Приказ МВД РК № 534 от 30.06.2023, редакция 2026 года), Закону «О дорожном движении», Правилам приема экзаменов и выдачи водительских удостоверений и другим официальным документам. У вопросов и правил указаны пункты. Официальный текст Правил опубликован на adilet.zan.kz.'),
            ('Точность и обновления', 'Каждый вопрос сверяется с текстом Правил: правильный ответ единственный, пункт указан верно, схема соответствует условию. Сайт обновляется при изменении Правил. Дата последнего обновления указана внизу страницы. Проект не является официальным изданием и не связан с Госкорпорацией «Правительство для граждан».'),
        ],
        'about_facts_h': 'Коротко о Жолдас',
        'about_facts': ['Вопросов с разбором: {n_q}', 'Дорожных знаков: {n_signs}', 'Тем учебника: {n_topics}', 'Категорий прав: {n_cat}', 'Языки: казахский, русский, английский', 'Пробный экзамен: 40 вопросов, 40 минут, 32 верных ответа'],
    },
    'kk': {
        'name': 'Жолдас', 'name_full': 'Жолдас ЖЖҚ', 'crumb_home': 'Басты бет', 'updated': 'Жаңартылды',
        'nav': {'exam': 'Емтихан', 'categories': 'Санаттар', 'signs': 'Белгілер', 'topics': 'Тақырыптар', 'faq': 'Сұрақтар', 'about': 'Жоба туралы'},
        'nav_label': 'Сайт бөлімдері', 'lang_label': 'Тіл', 'cta': 'Дайындықты бастау', 'cta_login': 'Кіру',
        'cta_note': 'Телефон нөмірі арқылы тіркелу. Оқу материалдары тегін.',
        'foot': 'Жолдас - ЖЖҚ емтиханына барлық санаттар бойынша жеке дайындық. ЖЖҚ бойынша оқу материалы (ҚР ІІМ-нің № 534 бұйрығы, 2026 жылғы редакция), ресми басылым емес. Қағидалардың ресми мәтіні мына сайтта:',
        'foot_check': 'Емтихан алдында eGov пен өзіңіздің арнаулы ХҚКО-дағы талаптарды тексеріңіз.',
        'privacy': 'Құпиялылық',
        'home_title': 'Жолдас ЖЖҚ: Қазақстанда жүргізуші куәлігі емтиханына дайындық 2026',
        'home_desc': 'ЖЖҚ 2026: {n_topics} тақырып, талдауы мен сызбалары бар {n_q} сұрақ, {n_signs} жол белгісі, арнаулы ХҚКО-дағыдай сынақ емтихан. Барлық {n_cat} санат бойынша жеке жоспар. Тегін.',
        'home_h1': 'Қазақстанда жүргізуші куәлігі емтиханына дайындық',
        'home_lead': 'Жолдас - ЖЖҚ 2026 теориясына A1-ден Tm-ге дейінгі барлық {n_cat} санат бойынша жеке дайындық. Емтихан күніне қарай жеке жоспар, оқулық, талдауы мен жағдай сызбалары бар {n_q} сұрақ, қателермен жұмыс және арнаулы ХҚКО пішіміндегі сынақ емтихан: 40 сұрақ, 40 минут, кемінде 32 дұрыс жауап.',
        'home_points': [
            'Емтихан күні мен санатқа қарай күн сайынғы жеке жоспар',
            'Оқулық: ЖЖҚ бойынша {n_topics} тақырып, қарапайым тілмен',
            'Талдауы, Қағидалар тармағына сілтемесі және сызбалары бар {n_q} сұрақ',
            'Атаулары мен мағыналары бар {n_signs} жол белгісі',
            'Қателермен жұмыс: қиын сұрақтар бекігенше қайта келеді',
            'Үш тіл: қазақша, орысша, ағылшынша',
        ],
        'home_explore': 'Тіркелмей-ақ біліп алуға болатын мәліметтер',
        'home_explore_links': [('exam', 'Қазақстанда жүргізуші куәлігі емтиханы қалай өтеді: теория, практика, қайта тапсыру'),
                               ('categories', 'A1-ден Tm-ге дейінгі барлық санат: жасы, өтілі, талаптар'),
                               ('signs', 'Қазақстанның жол белгілері: атаулары мен мағыналары'),
                               ('topics', 'ЖЖҚ тақырыптары: негізгі ережелер және жиі кездесетін қателер'),
                               ('faq', 'Емтихан туралы жиі қойылатын сұрақтарға жауаптар')],
        'exam_title': 'Қазақстанда жүргізуші куәлігі емтиханы 2026: теория, практика, қайта тапсыру',
        'exam_desc': 'Қазақстанда 2026 жылы жүргізуші куәлігі емтиханын қалай тапсыруға болады: теория (40 сұрақ, 40 минут, 32 дұрыс жауап), арнаулы ХҚКО автодромындағы практика, кезең-кезеңімен жол, қайта тапсыру мерзімдері.',
        'exam_h1': 'Қазақстанда 2026 жылы жүргізуші куәлігі емтиханы',
        'exam_lead': 'Қысқаша: теория - 40 минутта 40 сұрақ, тапсыру үшін кемінде 32 дұрыс жауап қажет; практика арнаулы ХҚКО-ның автоматтандырылған автодромында өтеді. Төменде куәлікке дейінгі жол, қайта тапсыру ережелері және 2026 жылғы өзгерістер берілген.',
        'exam_facts': ['Тесттегі сұрақ саны', 'Тестке берілетін минут', 'Кемінде дұрыс жауап', 'Теория тілі', 'Нәтиженің қолданылу мерзімі'],
        'exam_theory': 'Теориялық емтихан', 'exam_practical': 'Практикалық емтихан', 'exam_steps': 'Куәлікке дейінгі жол кезең-кезеңімен',
        'exam_retakes': 'Қайта тапсыру', 'exam_changes': '2026 жылы не өзгерді', 'exam_sources': 'Дереккөздер', 'exam_status': 'Мәртебесі',
        'exam_where': 'Қайда өтеді', 'exam_scoring': 'Қалай бағаланады',
        'cats_title': 'Қазақстандағы жүргізуші куәлігінің санаттары: A1, A, B, BE, C, D, Tm',
        'cats_desc': 'Қазақстандағы куәліктің барлық {n_cat} санаты мен кіші санаты: қандай көлік құралдары, қай жастан, өтіл қажет пе, теория мен практика қалай тапсырылады. ЖЖҚ 2026 анықтамалығы.',
        'cats_h1': 'Қазақстандағы жүргізуші куәлігінің санаттары',
        'cats_lead': 'Қазақстанда куәліктің {n_cat} санаты мен кіші санаты бар: мотоциклдерден (A1, A, B1) жеңіл автомобильдерге (B, BE), жүк автомобильдеріне (C1, C, C1E, CE), автобустарға (D1, D, D1E, DE), троллейбустар мен трамвайларға (Tb, Tm) дейін. Жасын, өтілін және емтихан тәртібін көру үшін санатты таңдаңыз.',
        'cats_col': ['Санат', 'Көлік құралдары', 'Жасы', 'Өтілі'],
        'cat_sections': {'vehicles': 'Қандай көлік құралдары', 'age': 'Ең төменгі жас', 'experience': 'Жүргізу өтілі',
                         'theory': 'Теориялық емтихан', 'practical': 'Практикалық емтихан', 'where': 'Қайда өтеді',
                         'car': 'Емтихан көлік құралы', 'exercises': 'Жаттығулар', 'sources': 'Ресми дереккөздер'},
        'cat_title': '{name}: жасы, өтілі, емтихан | Жолдас ЖЖҚ',
        'cat_other': 'Басқа санаттар',
        'signs_title': 'Қазақстанның жол белгілері: атаулары мен мағыналары 2026',
        'signs_desc': 'ҚР-дағы {n_signs} жол белгісінің каталогы: ескерту, басымдық, тыйым салатын, нұсқайтын, ақпараттық, сервис белгілері және тақтайшалар. Әр белгінің атауы, мағынасы және түсіндірмесі.',
        'signs_h1': 'Қазақстанның жол белгілері',
        'signs_lead': 'ЖЖҚ 1-қосымшасы бойынша жол белгілерінің каталогы: жеті топтағы {n_signs} белгі. Нақты атауын, мағынасын, түсіндірмесін және ол кездесетін емтихан сұрақтарын көру үшін белгіні ашыңыз.',
        'sign_title': '{code} «{name}» жол белгісі - мағынасы | Жолдас ЖЖҚ',
        'sign_h1': '{code} «{name}» жол белгісі',
        'sign_intro': '{code} «{name}» белгісі «{group}» тобына жатады.',
        'sign_labels': {'code': 'Нөмірі', 'name': 'Атауы', 'group': 'Тобы', 'meaning': 'Мағынасы', 'note': 'Түсіндірме', 'related': 'Осы топтағы ұқсас белгілер',
                        'questions': 'Осы белгі бойынша емтихан сұрақтары', 'answer': 'Дұрыс жауап', 'explain': 'Талдау', 'all': 'Барлық жол белгілері', 'img': 'Жол белгісі'},
        'group_blurb': {
            'Предупреждающие знаки': 'Жолдың қауіпті учаскесіне жақындағаны туралы ескертеді. Жүргізуші жағдайға сәйкес шаралар қабылдауы тиіс.',
            'Знаки приоритета': 'Қиылыстарды, жүру бөліктерінің қиылыстарын және жолдың тар учаскелерін жүріп өту кезектілігін белгілейді.',
            'Запрещающие знаки': 'Жүріс шектеулерін енгізеді немесе тоқтатады: кіруге, басып озуға, аялдауға тыйым, жылдамдықты, массаны, габариттерді шектеу.',
            'Предписывающие знаки': 'Жүрудің міндетті бағыттарын көрсетеді немесе жүруге тек белгілі көлік құралдарына рұқсат береді.',
            'Информационно-указательные знаки': 'Жүріс режимін енгізеді немесе тоқтатады, елді мекендер мен объектілердің орналасқан жерін хабарлайды.',
            'Знаки сервиса': 'Қызмет көрсету объектілерінің орналасқан жерін хабарлайды: медициналық көмек пункті, жанармай құю станциясы, демалыс орны.',
            'Знаки дополнительной информации (таблички)': 'Өздерімен бірге қолданылатын белгілердің әрекетін нақтылайды немесе шектейді: қашықтық, әрекет ету аймағы мен уақыты, көлік құралының түрі.',
        },
        'topics_title': 'ЖЖҚ тақырыптары: Қағиданың әр бөлімінің қысқаша талдауы',
        'topics_desc': 'ЖЖҚ 2026 бойынша {n_topics} тақырып: жалпы ережелер, жылдамдық, басып озу, қиылыстар, белгілер, таңба, алғашқы көмек, айыппұлдар. Әр тақырып бойынша - негізгісі және жиі кездесетін қателер.',
        'topics_h1': 'ЖЖҚ тақырыптары',
        'topics_lead': 'Жолдас оқулығы {n_topics} тақырыпқа бөлінген. Мұнда әрқайсысының қысқаша мазмұны берілген: тармақтарға сілтемесі бар негізгі ережелер және жүргізушілердің жиі кездесетін қателері.',
        'topic_title': '{title} - ЖЖҚ: негізгісі және жиі кездесетін қателер | Жолдас',
        'topic_sections': {'facts': 'Негізгісі', 'mistakes': 'Жиі кездесетін қателер', 'minutes': 'Оқуға кететін уақыт: {n} мин.', 'rules': 'Қағидалардың бөлімдері', 'more': 'Басқа тақырыптар',
                           'full': 'Толық сабақ, талдауы мен сызбалары бар сұрақтар тіркелгеннен кейін қолжетімді.', 'all': 'Барлық тақырыптар'},
        'topic_cats': 'Мына санаттарға',
        'faq_title': 'Қазақстанда жүргізуші куәлігі емтиханы туралы сұрақ-жауап | Жолдас ЖЖҚ',
        'faq_desc': 'Теорияда қанша сұрақ, қанша минут, қанша дұрыс жауап қажет, қайта қалай тапсыруға болады, куәлік қай жастан беріледі, тіркелу керек пе. ЖЖҚ 2026 бойынша жауаптар.',
        'faq_h1': 'Жүргізуші куәлігі емтиханы туралы жиі қойылатын сұрақтар',
        'faq_lead': 'Жауаптар Емтихан қабылдау және жүргізуші куәліктерін беру қағидаларына (2026 жылғы шілдедегі редакция) және «Жол жүрісі туралы» Заңға негізделген. Ақпарат анықтамалық сипатта: емтихан алдында талаптарды eGov-та және өзіңіздің арнаулы ХҚКО-да тексеріңіз.',
        'faq': [
            ('Қазақстанда теориялық емтиханда қанша сұрақ және қанша уақыт беріледі?',
             'Тестте 40 сұрақ бар, барлығына 40 минут беріледі. Тапсыру үшін кемінде 32 сұраққа дұрыс жауап беру керек, яғни 8 реттен артық қателесуге болмайды (Емтихан қабылдау қағидаларының 16, 17, 23-тармақтары).'),
            ('Теорияны қай тілде тапсыруға болады?',
             'Тест тілін өзіңіз таңдайсыз: қазақша, орысша немесе ағылшынша (16-тармақ). Қазақ немесе орыс тілін білмейтін шетелдіктер теорияны білікті аудармашымен тапсыра алады (6-тармақ).'),
            ('Теориялық емтихан нәтижесі қанша уақыт қолданылады?',
             'Теорияның оң нәтижесі алынған сәттен бастап 2 жыл қолданылады (Қағидалардың 2026 жылғы редакциясындағы 23-тармақ).'),
            ('Практикалық емтихан қалай өтеді?',
             'Практика арнаулы ХҚКО-ның автоматтандырылған автодромында, датчиктері мен бейнекамералары бар емтихан көлігінде өтеді. Нәтижені автоматты жүйе қояды: қателер үшін айыппұл балдары есептеледі, 100 балл жиналғанда емтихан тоқтатылып, «тапсырмады» деп белгіленеді (автодром әдістемесі).'),
            ('B санатты куәлікті қай жастан алуға болады?',
             '18 жастан («Жол жүрісі туралы» Заңның 74-бабы). Жергілікті әскери басқару органдарының жолдамасымен даярлықтан өткендер емтиханға 17 жастан жіберіледі, куәлік 18 жастан беріледі.'),
            ('Жүргізуші куәлігі емтиханын қанша уақыттан кейін қайта тапсыруға болады?',
             'Бірінші қайта тапсыру келесі жұмыс күніне тағайындалады. Екі сәтсіз әрекеттен кейін келесісі бір айдан ерте емес (11-2-тармақ). Теорияда ережені бұзсаңыз (кеңес беру, телефон, залдан шығу), қайта тапсыру 3 айдан ерте емес (24-тармақ).'),
            ('Емтиханға жазылу үшін не қажет?',
             '073/е нысанындағы медициналық анықтама, жүргізуге оқыту ұйымында курсты бітіргені туралы куәлік және eGov порталы, eGov Mobile қосымшасы немесе ХҚКО арқылы жазылу. Жазылу кезінде биометриялық сәйкестендіру өтеді (6, 11-1, 11-2-тармақтар).'),
            ('Жолдаста тіркелу керек пе және бұл қанша тұрады?',
             '40 сұрақтан тұратын бір сынақ тестті тіркелмей-ақ тапсыруға болады. Жеке жоспар, оқулық және талдауы бар сұрақтар бойынша оқу үшін телефон нөмірі арқылы тіркелу керек. Жолдастағы оқу тегін.'),
            ('Бұл арнаулы ХҚКО-ның ресми сұрақтары ма?',
             'Жоқ. Ресми сұрақ базасы жарияланбайды. Жолдас - қолданыстағы ЖЖҚ бойынша оқу материалы: сұрақтар Қағида мәтіні бойынша құрастырылған, әрқайсысында тармақ көрсетілген. Сынақ емтихан нақты емтихан пішінін қайталайды: 40 сұрақ, 40 минут, кемінде 32 дұрыс жауап.'),
            ('Жолдаста қанша сұрақ бар және қандай санаттарға арналған?',
             'Базада талдауы мен сызбалары бар {n_q} сұрақ, {n_signs} жол белгісі және {n_topics} тақырып бар. Барлық {n_cat} санат қамтылған: A1, A, B1, B, BE, C1, C, C1E, CE, D1, D, D1E, DE, Tb, Tm. Санат ерекшеліктері бойынша сұрақтар тек оларға қажет адамдарға көрсетіледі.'),
        ],
        'about_title': 'Жолдас жобасы туралы: ЖЖҚ емтиханына тегін дайындық',
        'about_desc': 'Жолдас дегеніміз не: Қазақстанның ЖЖҚ теориясына қазақша, орысша және ағылшынша жеке дайындық. Курс қалай құрылған, материалдар қайдан алынған және дәлдік қалай тексеріледі.',
        'about_h1': 'Жолдас жобасы туралы',
        'about_sections': [
            ('Бұл не', 'Жолдас - Қазақстанда жүргізуші куәлігі емтиханына дайындалуға арналған сайт. Ол ЖЖҚ 2026-ны жеке жоспар бойынша үйренуге көмектеседі: оқулық, талдауы мен жағдай сызбалары бар сұрақтар, қателермен жұмыс және арнаулы ХҚКО пішіміндегі сынақ емтихан.'),
            ('Кімге арналған', 'A1-ден Tm-ге дейінгі кез келген {n_cat} санат бойынша теорияға дайындалып жүрген және қазақша, орысша немесе ағылшынша оқығысы келетіндерге арналған. Оқу тегін, тек телефон нөмірі арқылы тіркелу керек.'),
            ('Материалдар қайдан', 'Материалдар ҚР Жол жүрісі қағидаларына (ҚР ІІМ-нің 30.06.2023 жылғы № 534 бұйрығы, 2026 жылғы редакция), «Жол жүрісі туралы» Заңға, Емтихан қабылдау және жүргізуші куәліктерін беру қағидаларына және басқа да ресми құжаттарға сәйкес құрастырылған. Сұрақтар мен ережелерде тармақтар көрсетілген. Қағидалардың ресми мәтіні adilet.zan.kz сайтында жарияланған.'),
            ('Дәлдік және жаңарту', 'Әр сұрақ Қағида мәтінімен салыстырылады: дұрыс жауап біреу ғана, тармақ дұрыс көрсетілген, сызба шартқа сәйкес келеді. Қағидалар өзгергенде сайт жаңартылады. Соңғы жаңарту күні беттің төменгі жағында көрсетілген. Жоба ресми басылым емес және «Азаматтарға арналған үкімет» мемлекеттік корпорациясымен байланысты емес.'),
        ],
        'about_facts_h': 'Жолдас туралы қысқаша',
        'about_facts': ['Талдауы бар сұрақтар: {n_q}', 'Жол белгілері: {n_signs}', 'Оқулық тақырыптары: {n_topics}', 'Куәлік санаттары: {n_cat}', 'Тілдері: қазақша, орысша, ағылшынша', 'Сынақ емтихан: 40 сұрақ, 40 минут, 32 дұрыс жауап'],
    },
    'en': {
        'name': 'Joldas', 'name_full': 'Joldas', 'crumb_home': 'Home', 'updated': 'Updated',
        'nav': {'exam': 'Test', 'categories': 'Categories', 'signs': 'Road signs', 'topics': 'Topics', 'faq': 'FAQ', 'about': 'About'},
        'nav_label': 'Site sections', 'lang_label': 'Language', 'cta': 'Start preparing', 'cta_login': 'Log in',
        'cta_note': 'Sign up with a phone number. Study materials are free of charge.',
        'foot': 'Joldas - personal preparation for the Kazakhstan driving theory test in all categories. Study material based on the Road Traffic Rules (MIA Order No. 534, 2026 edition), not an official publication. The official text of the Rules is at',
        'foot_check': 'Before the test, check the conditions on eGov and with your specialised PSC.',
        'privacy': 'Privacy',
        'home_title': 'Joldas: Kazakhstan Driving Theory Test Prep 2026 (Free Practice)',
        'home_desc': 'Kazakhstan driving theory test 2026: {n_q} questions with explanations and diagrams, {n_signs} road signs, a mock exam and a personal plan for all {n_cat} categories. Free.',
        'home_h1': 'Prepare for the Kazakhstan driving theory test',
        'home_lead': 'Joldas (Жолдас) is personal preparation for the Kazakhstan driving theory test 2026 in all {n_cat} licence categories, from A1 to Tm. It gives you a study plan built around your test date, a textbook, {n_q} questions with explanations and traffic diagrams, mistake review and a mock exam in the official format: 40 questions, 40 minutes, at least 32 correct answers.',
        'home_points': [
            'A personal daily plan based on your test date and category',
            'Textbook: {n_topics} topics of the Kazakhstan Road Traffic Rules in plain language',
            '{n_q} questions with explanations, references to Rules clauses and diagrams',
            '{n_signs} road signs with names and meanings',
            'Mistake review: hard questions come back until they stick',
            'Three languages: Kazakh, Russian and English',
        ],
        'home_explore': 'What you can read without signing up',
        'home_explore_links': [('exam', 'How the driving test works in Kazakhstan: theory, practical, retakes'),
                               ('categories', 'All licence categories from A1 to Tm: age, experience, requirements'),
                               ('signs', 'Road signs of Kazakhstan with names and meanings'),
                               ('topics', 'Topics of the Road Traffic Rules: key points and common mistakes'),
                               ('faq', 'Answers to frequently asked questions about the test')],
        'exam_title': 'Kazakhstan Driving Test 2026: Theory, Practical, Retakes',
        'exam_desc': 'How to pass the driving test in Kazakhstan in 2026: the theory test (40 questions, 40 minutes, 32 correct), the practical test at a specialised PSC test ground, the step-by-step route to a licence, retake rules and 2026 changes.',
        'exam_h1': 'The driving test in Kazakhstan in 2026',
        'exam_lead': 'In short: the theory test is 40 questions in 40 minutes and you need at least 32 correct answers; the practical test takes place at an automated test ground of a specialised PSC. Below: the route to a licence, the retake rules and what changed in 2026.',
        'exam_facts': ['Questions in the test', 'Minutes for the test', 'Minimum correct answers', 'Theory test language', 'Validity of a pass'],
        'exam_theory': 'The theory test', 'exam_practical': 'The practical test', 'exam_steps': 'The route to a licence, step by step',
        'exam_retakes': 'Retakes', 'exam_changes': 'What changed in 2026', 'exam_sources': 'Sources', 'exam_status': 'Status',
        'exam_where': 'Where it takes place', 'exam_scoring': 'How it is scored',
        'cats_title': 'Driving Licence Categories in Kazakhstan: A1, A, B1, B, BE, C1, C, D1, D, Tb, Tm',
        'cats_desc': 'All {n_cat} driving licence categories and subcategories in Kazakhstan: which vehicles, minimum age, experience required, and how the theory and practical tests work. Reference based on the Road Traffic Rules 2026.',
        'cats_h1': 'Driving licence categories in Kazakhstan',
        'cats_lead': 'Kazakhstan has {n_cat} licence categories and subcategories: from motorcycles (A1, A, B1) to cars (B, BE), trucks (C1, C, C1E, CE), buses (D1, D, D1E, DE), trolleybuses and trams (Tb, Tm). Choose a category to see the age, experience and test procedure.',
        'cats_col': ['Category', 'Vehicles', 'Age', 'Experience'],
        'cat_sections': {'vehicles': 'Which vehicles', 'age': 'Minimum age', 'experience': 'Driving experience',
                         'theory': 'The theory test', 'practical': 'The practical test', 'where': 'Where it takes place',
                         'car': 'Test vehicle', 'exercises': 'Exercises', 'sources': 'Official sources'},
        'cat_title': '{name} - age, experience, test | Joldas',
        'cat_other': 'Other categories',
        'signs_title': 'Road Signs of Kazakhstan with Names and Meanings (2026)',
        'signs_desc': 'A catalogue of {n_signs} road signs of Kazakhstan: warning, priority, prohibitory, mandatory, information, service signs and plates. The name, meaning and explanation of each sign.',
        'signs_h1': 'Road signs of Kazakhstan',
        'signs_lead': 'A catalogue of road signs from Annex 1 to the Road Traffic Rules: {n_signs} signs in seven groups. Open a sign to see its exact name, meaning, explanation and the test questions where it appears.',
        'sign_title': 'Road sign {code}: {name} - meaning | Joldas',
        'sign_h1': 'Road sign {code}: {name}',
        'sign_intro': 'Sign {code} (“{name}”) belongs to the group “{group}”.',
        'sign_labels': {'code': 'Number', 'name': 'Name', 'group': 'Group', 'meaning': 'Meaning', 'note': 'Explanation', 'related': 'Related signs in this group',
                        'questions': 'Test questions about this sign', 'answer': 'Correct answer', 'explain': 'Explanation', 'all': 'All road signs', 'img': 'Road sign'},
        'group_blurb': {
            'Предупреждающие знаки': 'They warn that a dangerous section of road is ahead. The driver must take action suited to the situation.',
            'Знаки приоритета': 'They set the order of passing intersections, crossings of carriageways and narrow sections of road.',
            'Запрещающие знаки': 'They introduce or lift traffic restrictions: no entry, no overtaking, no stopping, limits on speed, weight and size.',
            'Предписывающие знаки': 'They show mandatory directions of travel or allow travel only for certain vehicles.',
            'Информационно-указательные знаки': 'They introduce or lift a traffic regime and show where towns and facilities are.',
            'Знаки сервиса': 'They show where service facilities are: first aid, filling stations, rest areas.',
            'Знаки дополнительной информации (таблички)': 'They clarify or limit the effect of the signs they are used with: distance, zone and time of effect, type of vehicle.',
        },
        'topics_title': 'Kazakhstan Road Traffic Rules by Topic: Key Points and Common Mistakes',
        'topics_desc': '{n_topics} topics of the Kazakhstan Road Traffic Rules 2026: general provisions, speed, overtaking, intersections, signs, markings, first aid, fines. For each topic - the key points and common mistakes.',
        'topics_h1': 'Topics of the Road Traffic Rules',
        'topics_lead': 'The Joldas textbook is split into {n_topics} topics. Here is a summary of each: the main rules with references to clauses and the mistakes drivers make most often.',
        'topic_title': '{title} - Kazakhstan Road Rules: key points | Joldas',
        'topic_sections': {'facts': 'Key points', 'mistakes': 'Common mistakes', 'minutes': 'Study time: {n} min.', 'rules': 'Chapters of the Rules', 'more': 'More topics',
                           'full': 'The full lesson, questions with explanations and diagrams are available after you sign up.', 'all': 'All topics'},
        'topic_cats': 'For categories',
        'faq_title': 'Driving Test in Kazakhstan: Frequently Asked Questions | Joldas',
        'faq_desc': 'How many questions and minutes in the theory test, how many correct answers you need, how to retake, the minimum age for a licence and whether you need to register. Answers based on the 2026 Rules.',
        'faq_h1': 'Frequently asked questions about the driving test',
        'faq_lead': 'The answers are based on the Rules for Examinations and Issuing Driving Licences (July 2026 edition) and the Road Traffic Act. The information is for reference: before the test, check the conditions on eGov and with your specialised PSC.',
        'faq': [
            ('How many questions and how much time is there in the theory test in Kazakhstan?',
             'The test has 40 questions and you have 40 minutes for all of them. To pass, you must answer at least 32 correctly, that is, you can make no more than 8 mistakes (paras. 16, 17, 23 of the Examination Rules).'),
            ('In which language can I take the theory test?',
             'You choose the language of the test: Kazakh, Russian or English (para. 16). Foreigners who do not speak Kazakh or Russian may take the theory test with a qualified interpreter (para. 6).'),
            ('How long is a theory test pass valid?',
             'A pass in the theory test is valid for 2 years from the date it is obtained (para. 23 of the Rules, 2026 edition).'),
            ('How does the practical test work?',
             'The practical test takes place at an automated test ground of a specialised PSC, in an exam car fitted with sensors and video cameras. An automatic system gives the result: mistakes earn penalty points, and at 100 points the test is stopped and marked “fail” (test ground methodology).'),
            ('From what age can I get a category B licence?',
             'From 18 (art. 74 of the Road Traffic Act). People who have completed training on a referral from the local military administration bodies are admitted to the test from 17, and the licence is issued from 18.'),
            ('How soon can I retake the driving test?',
             'The first retake is scheduled for the next working day. After two failed attempts, the next one is allowed no earlier than one month later (para. 11-2). If you break the rules during the theory test (prompting, phone, leaving the room), a retake is possible no earlier than 3 months later (para. 24).'),
            ('What do I need to book the test?',
             'A medical certificate, Form No. 073/u, a certificate of completion of a course at a driver training organisation, and a booking through the eGov portal, the eGov Mobile app or a PSC. Biometric identification is carried out when you apply (paras. 6, 11-1, 11-2).'),
            ('Do I need to register on Joldas and what does it cost?',
             'You can take one mock test of 40 questions without registering. To study with a personal plan, the textbook and questions with explanations you need to register with a phone number. Learning on Joldas is free.'),
            ('Are these the official questions of the specialised PSC?',
             'No. The official question bank is not published. Joldas is study material based on the current Road Traffic Rules: the questions are written from the text of the Rules and each one cites a clause. The mock exam follows the format of the real one: 40 questions, 40 minutes, at least 32 correct answers.'),
            ('How many questions does Joldas have and for which categories?',
             'The bank has {n_q} questions with explanations and diagrams, {n_signs} road signs and {n_topics} topics. All {n_cat} categories are covered: A1, A, B1, B, BE, C1, C, C1E, CE, D1, D, D1E, DE, Tb, Tm. Questions specific to a category are shown only to those who need them.'),
        ],
        'about_title': 'About Joldas: Free Preparation for the Kazakhstan Driving Theory Test',
        'about_desc': 'What Joldas is: personal preparation for the Kazakhstan driving theory test in Kazakh, Russian and English. How the course works, where the materials come from and how accuracy is checked.',
        'about_h1': 'About Joldas',
        'about_sections': [
            ('What it is', 'Joldas (Жолдас, Kazakh for “travelling companion”) is a website for preparing for the driving licence test in Kazakhstan. It helps you learn the 2026 Road Traffic Rules with a personal plan: a textbook, questions with explanations and traffic diagrams, mistake review and a mock exam in the format of the specialised PSC.'),
            ('Who it is for', 'For anyone preparing for the theory test in any of the {n_cat} categories, from A1 to Tm, who wants to study in Kazakh, Russian or English. Learning is free; you only need to register with a phone number.'),
            ('Where the materials come from', 'The materials are written from the Road Traffic Rules of Kazakhstan (Ministry of Internal Affairs Order No. 534 of 30.06.2023, 2026 edition), the Road Traffic Act, the Rules for Examinations and Issuing Driving Licences and other official documents. Questions and rules cite the clauses. The official text of the Rules is published on adilet.zan.kz.'),
            ('Accuracy and updates', 'Every question is checked against the text of the Rules: one correct answer, the right clause cited, a diagram that matches the question. The site is updated when the Rules change. The date of the last update is shown at the bottom of the page. The project is not an official publication and is not affiliated with the State Corporation “Government for Citizens”.'),
        ],
        'about_facts_h': 'Joldas at a glance',
        'about_facts': ['Questions with explanations: {n_q}', 'Road signs: {n_signs}', 'Textbook topics: {n_topics}', 'Licence categories: {n_cat}', 'Languages: Kazakh, Russian, English', 'Mock exam: 40 questions, 40 minutes, 32 correct answers'],
    },
}

# ИИ-краулеры: токены robots.txt (обучение, поиск, действия по запросу пользователя)
AI_BOTS = ['GPTBot', 'OAI-SearchBot', 'ChatGPT-User', 'ClaudeBot', 'Claude-SearchBot', 'Claude-User', 'anthropic-ai',
           'PerplexityBot', 'Perplexity-User', 'Google-Extended', 'GoogleOther', 'Applebot', 'Applebot-Extended',
           'meta-externalagent', 'meta-externalfetcher', 'Amazonbot', 'DuckAssistBot', 'MistralAI-User', 'cohere-ai',
           'YandexBot', 'YandexAdditional', 'Bingbot', 'bingbot', 'CCBot', 'Bytespider', 'Diffbot']
